# Generated by Django 2.0.5 on 2018-05-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djomeka_app', '0002_auto_20180522_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='attributes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
