# Generated by Django 2.0.5 on 2018-05-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djomeka_app', '0003_auto_20180522_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='files',
            field=models.FileField(upload_to='static/'),
        ),
    ]
